CREATE TABLE `cps_blacklist_email` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `created_by_id` bigint(20) DEFAULT NULL,
  `date_created` datetime NOT NULL,
  `email` varchar(255) NOT NULL,
  `last_updated` datetime NOT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  `remark` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_cy6nq9l2l71dv1w8v4f0rcvug` (`created_by_id`),
  KEY `FK_1nh7f1x7tvrcr15hudghqk2e5` (`modified_by_id`),
  CONSTRAINT `FK_1nh7f1x7tvrcr15hudghqk2e5` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_cy6nq9l2l71dv1w8v4f0rcvug` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_camera_usage` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `business_type` varchar(255) NOT NULL,
  `business_type_others` varchar(255) DEFAULT NULL,
  `date_created` datetime NOT NULL,
  `last_updated` datetime NOT NULL,
  `member_id` bigint(20) NOT NULL,
  `created_by_id` bigint(20) DEFAULT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ddkv8w7cugnal2pw6pnogx6m8` (`member_id`),
  KEY `FK_nphdv4fn6bf7a0bu518377y5x` (`created_by_id`),
  KEY `FK_i8akhm2xl6h03clb7mjbpks32` (`modified_by_id`),
  CONSTRAINT `FK_ddkv8w7cugnal2pw6pnogx6m8` FOREIGN KEY (`member_id`) REFERENCES `cps_member` (`id`),
  CONSTRAINT `FK_i8akhm2xl6h03clb7mjbpks32` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_nphdv4fn6bf7a0bu518377y5x` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1629 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_camera_usage_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `camera_usage_id` bigint(20) NOT NULL,
  `date_created` datetime NOT NULL,
  `detail_type` varchar(255) NOT NULL,
  `detail_type_others` varchar(255) DEFAULT NULL,
  `last_updated` datetime NOT NULL,
  `created_by_id` bigint(20) DEFAULT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ci35qsgpu5kmjrs5u9c7kgu6h` (`camera_usage_id`),
  KEY `FK_2wyoaep6mv6712gheefuw2iyw` (`created_by_id`),
  KEY `FK_qebge9ntf35uwausdtehy8m08` (`modified_by_id`),
  CONSTRAINT `FK_2wyoaep6mv6712gheefuw2iyw` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_ci35qsgpu5kmjrs5u9c7kgu6h` FOREIGN KEY (`camera_usage_id`) REFERENCES `cps_camera_usage` (`id`),
  CONSTRAINT `FK_qebge9ntf35uwausdtehy8m08` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=153 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_country` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `country_id` bigint(20) NOT NULL,
  `date_created` datetime NOT NULL,
  `last_updated` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_ewiargbidlieb6nn67xwd50gy` (`country_id`),
  CONSTRAINT `FK_ewiargbidlieb6nn67xwd50gy` FOREIGN KEY (`country_id`) REFERENCES `country` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_equipment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `criteria` int(11) DEFAULT NULL,
  `date_created` datetime NOT NULL,
  `equipment_type` varchar(255) NOT NULL,
  `last_updated` datetime NOT NULL,
  `name` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `legacy_id` bigint(20) DEFAULT NULL,
  `created_by_id` bigint(20) DEFAULT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_h0njs9asanykdg6s01gysvhty` (`created_by_id`),
  KEY `FK_plttn9q5gdtfahekxxtikvbpb` (`modified_by_id`),
  CONSTRAINT `FK_h0njs9asanykdg6s01gysvhty` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_plttn9q5gdtfahekxxtikvbpb` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10026 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_invitation` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `created_by_id` bigint(20) DEFAULT NULL,
  `date_created` datetime NOT NULL,
  `email` varchar(255) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `last_updated` datetime NOT NULL,
  `message` text,
  `modified_by_id` bigint(20) DEFAULT NULL,
  `sent_count` int(11) NOT NULL,
  `sent_date` datetime DEFAULT NULL,
  `site_id` bigint(20) NOT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_5fnnysefrwx21ctw5ipowhog9` (`created_by_id`),
  KEY `FK_qn0sawi0faypnxf49urdvnhho` (`modified_by_id`),
  KEY `FK_mho6lvpi3adjf5n66dnd5w6n5` (`site_id`),
  CONSTRAINT `FK_5fnnysefrwx21ctw5ipowhog9` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_mho6lvpi3adjf5n66dnd5w6n5` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`),
  CONSTRAINT `FK_qn0sawi0faypnxf49urdvnhho` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_member` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `address` text NOT NULL,
  `card_expiry_date` datetime DEFAULT NULL,
  `card_issue_date` datetime DEFAULT NULL,
  `card_name` varchar(255) DEFAULT NULL,
  `city` varchar(255) NOT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `country_id` bigint(20) NOT NULL,
  `country_verify_date` datetime DEFAULT NULL,
  `country_verify_status` int(11) DEFAULT NULL,
  `cps_no` varchar(255) DEFAULT NULL,
  `cspl_status` int(11) DEFAULT NULL,
  `cspl_verify_date` datetime DEFAULT NULL,
  `date_created` datetime NOT NULL,
  `email` varchar(255) NOT NULL,
  `enquiry_status` varchar(255) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `is_lecturer` bit(1) NOT NULL DEFAULT b'0',
  `last_updated` datetime NOT NULL,
  `mailing_list_status` int(11) DEFAULT NULL,
  `mc_received_date` datetime DEFAULT NULL,
  `member_status` varchar(255) NOT NULL,
  `member_type` varchar(255) NOT NULL,
  `nationality` varchar(255) DEFAULT NULL,
  `passport_no` varchar(255) NOT NULL,
  `province` varchar(255) NOT NULL,
  `remark` text,
  `salutation` varchar(255) NOT NULL,
  `salutation_other` varchar(255) DEFAULT NULL,
  `send_mc_to_nso_date` datetime DEFAULT NULL,
  `site_id` bigint(20) NOT NULL,
  `submission_date` datetime NOT NULL,
  `tel_home` varchar(255) DEFAULT NULL,
  `tel_mobile` varchar(255) DEFAULT NULL,
  `tel_office` varchar(255) DEFAULT NULL,
  `welcome_kit_sent_date` datetime DEFAULT NULL,
  `working_certificate` varchar(255) DEFAULT NULL,
  `zip_code` varchar(255) DEFAULT NULL,
  `created_by_id` bigint(20) DEFAULT NULL,
  `invitation_id` bigint(20) DEFAULT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_6cgw45g6gbd90t646i58vix4g` (`email`),
  KEY `FK_1dtjkjc94cadlc6mtk4ythp9f` (`country_id`),
  KEY `FK_9nnob3gk3n3y0r5d1nvvqooym` (`site_id`),
  KEY `FK_rmcsci6xk4bd8gra0c8xxpkms` (`created_by_id`),
  KEY `FK_ml67c8guxik81sa6mnrrpw524` (`invitation_id`),
  KEY `FK_l6659tvcnn9f6abkfw5lack0d` (`modified_by_id`),
  CONSTRAINT `FK_1dtjkjc94cadlc6mtk4ythp9f` FOREIGN KEY (`country_id`) REFERENCES `country` (`id`),
  CONSTRAINT `FK_9nnob3gk3n3y0r5d1nvvqooym` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`),
  CONSTRAINT `FK_l6659tvcnn9f6abkfw5lack0d` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_ml67c8guxik81sa6mnrrpw524` FOREIGN KEY (`invitation_id`) REFERENCES `cps_invitation` (`id`),
  CONSTRAINT `FK_rmcsci6xk4bd8gra0c8xxpkms` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1742 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_member_equipment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `date_created` datetime NOT NULL,
  `equipment_id` bigint(20) NOT NULL,
  `last_updated` datetime NOT NULL,
  `member_id` bigint(20) NOT NULL,
  `retain` bit(1) NOT NULL DEFAULT b'1',
  `serial_number` varchar(255) NOT NULL,
  `created_by_id` bigint(20) DEFAULT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK1b600c9624c406482f70943b8ffd` (`serial_number`,`member_id`,`equipment_id`),
  KEY `FK_psnou3oiqt9uy3310r4dp81a6` (`equipment_id`),
  KEY `FK_pqnk5sjq5k1aknyh80oeah7l9` (`member_id`),
  KEY `FK_gwlp5dqd6h1xe01cla6mmh7bi` (`created_by_id`),
  KEY `FK_3508tw3ldwdncxvgcrksxuqm8` (`modified_by_id`),
  CONSTRAINT `FK_3508tw3ldwdncxvgcrksxuqm8` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_gwlp5dqd6h1xe01cla6mmh7bi` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_pqnk5sjq5k1aknyh80oeah7l9` FOREIGN KEY (`member_id`) REFERENCES `cps_member` (`id`),
  CONSTRAINT `FK_psnou3oiqt9uy3310r4dp81a6` FOREIGN KEY (`equipment_id`) REFERENCES `cps_equipment` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23444 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_renewal` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `available` bit(1) NOT NULL DEFAULT b'1',
  `date_created` datetime NOT NULL,
  `form_data` text,
  `last_updated` datetime NOT NULL,
  `member_id` bigint(20) NOT NULL,
  `token` varchar(255) NOT NULL,
  `used_by` text,
  `used_on` datetime DEFAULT NULL,
  `renewal_deadline` datetime DEFAULT NULL,
  `sent` bit(1) NOT NULL DEFAULT b'0',
  `submission_status` bit(1) NOT NULL DEFAULT b'0',
  `created_by_id` bigint(20) DEFAULT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_33v6hpqgkj5mvcf4hq4jmhl5j` (`member_id`),
  KEY `FK_8t9p03i4lfls63etj51cse72i` (`created_by_id`),
  KEY `FK_ie104ucbx6bnsmdrvxoyt6aub` (`modified_by_id`),
  CONSTRAINT `FK_33v6hpqgkj5mvcf4hq4jmhl5j` FOREIGN KEY (`member_id`) REFERENCES `cps_member` (`id`),
  CONSTRAINT `FK_8t9p03i4lfls63etj51cse72i` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_ie104ucbx6bnsmdrvxoyt6aub` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=756 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_sensor_cleaning` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `created_by_id` bigint(20) DEFAULT NULL,
  `date_created` datetime NOT NULL,
  `date_of_service` datetime NOT NULL,
  `is_external` bit(1) NOT NULL DEFAULT b'0',
  `last_updated` datetime NOT NULL,
  `member_id` bigint(20) NOT NULL,
  `member_equipment_id` bigint(20) DEFAULT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `release_date` datetime DEFAULT NULL,
  `remark` text,
  `serial` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_9lts0kope1ox37uqpeu469qfk` (`created_by_id`),
  KEY `FK_nyqa61eageqlepy9by05d3jjr` (`member_id`),
  KEY `FK_550h514qaebk08n0shrv1hnj7` (`member_equipment_id`),
  KEY `FK_3daas36kveiweal4htlpwj627` (`modified_by_id`),
  CONSTRAINT `FK_3daas36kveiweal4htlpwj627` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_550h514qaebk08n0shrv1hnj7` FOREIGN KEY (`member_equipment_id`) REFERENCES `cps_member_equipment` (`id`),
  CONSTRAINT `FK_9lts0kope1ox37uqpeu469qfk` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_nyqa61eageqlepy9by05d3jjr` FOREIGN KEY (`member_id`) REFERENCES `cps_member` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cps_template` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `content` mediumtext,
  `created_by_id` bigint(20) DEFAULT NULL,
  `date_created` datetime NOT NULL,
  `language_id` varchar(5) NOT NULL,
  `last_updated` datetime NOT NULL,
  `modified_by_id` bigint(20) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `site_id` bigint(20) NOT NULL,
  `status` varchar(255) DEFAULT NULL,
  `template_type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_56kuobpvjqhom4i5ey3xtygf3` (`created_by_id`),
  KEY `FK_2w14cd57e8a35myuwl48hh95b` (`language_id`),
  KEY `FK_s7g7oncjkelfa1knpm28t5p0x` (`modified_by_id`),
  KEY `FK_651e3mntge5y9brsy8r36em8j` (`site_id`),
  CONSTRAINT `FK_2w14cd57e8a35myuwl48hh95b` FOREIGN KEY (`language_id`) REFERENCES `lang` (`id`),
  CONSTRAINT `FK_56kuobpvjqhom4i5ey3xtygf3` FOREIGN KEY (`created_by_id`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_651e3mntge5y9brsy8r36em8j` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`),
  CONSTRAINT `FK_s7g7oncjkelfa1knpm28t5p0x` FOREIGN KEY (`modified_by_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
